### ISSUE TITLE
[BUG] no download for loader n allat

### ISSUE THREAD

**Issue by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [anditv21/panel#65]
im not sure if this is an issue with gamesense theme specifically, but while trying to access the front page and allat, theres no download for the loader or nothing whilst using the admin account

**Comment by anditv21** [comment]
Thank you for drawing attention to this.
Unfortunately, I have the gamesense theme a bit neglected thereby probably a few small errors have arisen.

I hope these are all fixed with the latest [release](https://github.com/anditv21/panel/releases/tag/v0.2.6).

Greetings Andreas

**Comment by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [comment]
with the latest release of this, its still the same
![image](https://user-images.githubusercontent.com/103281116/211141351-9f00fbae-5790-4bb7-bd3b-c5e21297eb12.png)
![image](https://user-images.githubusercontent.com/103281116/211141356-8e4a9828-4155-42c0-900d-c56c5401f882.png)
![image](https://user-images.githubusercontent.com/103281116/211141361-b231f860-daad-418d-9896-d0e21905144f.png)

**Comment by anditv21** [comment]
I will close this issue as it is related to #66.
